name: Acorn Linux Build Test

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libvlc-dev libvlccore-dev
      - name: Install Haxe dependencies
        run: |
          haxelib setup ~/haxelib
          sh ./setup/unix.sh
      - name: Compile Linux
        run: haxelib run lime build Project.xml linux -D officialBuild
